### PR TITLE
Fix for Component::init() methods order

### PR DESCRIPTION
**Pull request by erickskrauch**
https://github.com/hellowearemito/yii2-sentry/pull/4#issuecomment-265571542

### CODE REVIEW

**Comment by albertborsos** [comment]
Thanks for your PR!

I put this validator to the beginning of the init function to check the validity of the DSN before the app goes into production.

Once it happened that a wrong DSN has been configured by a programmer who met first with sentry, and it turns out only in production. Thats why I can not merge this modification. Thank you for your understanding.

**Comment by erickskrauch** [comment]
But look at this from another side. In test environment (codeception) I need to disable this component, but not remove from service locator. I don't pass dsn for test configuration, because I do not want to record exceptions while performing tests. So, in current realization I must specify some fake dsn. Is this correct behavior?

**Comment by nkovacs** [comment]
Why do you need to keep it in the service locator?
What does your project's configuration look like?
We add the sentry component with a valid dsn to the global configuration, but then disable it in the development and test environments.

**Comment by ItsReddi** [comment]
Well,
private DSN should not be in a global configuration, like passwds, keys and so on.
For those privates yii provides local configurations.

But its a good way to provide the components in the 'global config'.

'global conf'
```php
'sentry' => [
            'class' => 'mito\sentry\Component',
            'dsn' => '', // private DSN set it in your local config if needed
            'environment' => 'staging', // if not set, the default is `staging`
            'enabled' => !YII_DEBUG && !YII_ENV_TEST
            ],
```

the developer can activate his own project if needed. and production is overwriting this 'global conf' anyway. 
But that setup (and the above description is the yii2 default advanced setup behavior (dont know about basic)) is not possible if you validate the dsn every time.

Would it be possible to add something forceDSNValidation? ~defaults: true
This would not break your config setup and it would be possible to follow the security guidelines for configs.

**Comment by albertborsos** [comment]
Thanks for your PR, we have reconsidered this issue and now it is available since `1.0.4`

**Comment by erickskrauch** [comment]
Holy shit, justice triumphed in the universe!

**Pull request closed without merging**
